[package]
name = "kobo-weather"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.25.0"
usvg = "0.25.0"
tiny-skia = "0.8.2"
anyhow = "1.0.66"