[package]
name = "kobo-weather"
version = "0.1.0"
edition = "2021"

[[example]]
name = "preview"
path = "examples/preview.rs"

[dev-dependencies]
show-image = "0.13.1"

[dependencies]
resvg = "0.25.0"
usvg = "0.25.0"
tiny-skia = "0.8.2"
anyhow = "1.0.66"