[tasks.format]
description = "Runs the cargo rustfmt plugin."
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.install-deps.mac]
script = '''
if ! command -v armv7-unknown-linux-musleabihf-gcc &> /dev/null
then
    brew tap messense/macos-cross-toolchains
    brew install armv7-unknown-linux-musleabihf
fi
'''

[tasks.install-target]
description = "Install required targets"
command = "rustup"
args = ["target", "add", "armv7-unknown-linux-musleabihf"]

[tasks.build]
dependencies = ["install-deps", "install-target"]
description = "Build the project for Kobo."
env = { "CC_armv7_unknown_linux_musleabihf" = "armv7-unknown-linux-musleabihf-gcc", "CXX_armv7_unknown_linux_musleabihf" = "armv7-unknown-linux-musleabihf-g++",  "AR_armv7_unknown_linux_musleabihf" = "armv7-unknown-linux-musleabihf-ar", "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER" = "armv7-unknown-linux-musleabihf-gcc"}
command = "cargo"
args = ["build", "--release", "--target", "armv7-unknown-linux-musleabihf", "--verbose"]

[tasks.preview]
description = "Preview the dashboard."
command = "cargo"
args = ["run", "--example", "preview"]