[tasks.format]
description = "Runs the cargo rustfmt plugin."
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.build]
description = "Build the project for Kobo."
install_crate = "cross"
command = "cross"
args = ["build", "--release"]

[tasks.preview]
description = "Preview the dashboard."
command = "cargo"
args = ["run", "--example", "preview"]